### ISSUE TITLE
imac12,2 Board-id correction

### ISSUE THREAD

**Issue by rtcl777** [Piker-Alpha/RevoBoot#2]
Hello...:)
For your info Regarding cd83c021f8

imac12,1 should be Mac-942B5 'B' F58194151B not Mac-942B5 '9' F58194151B
imac12,2 should be Mac-942B5 '9' F58194171B not Mac-942B5 'B' F58194171B

**Comment by Piker-Alpha** [comment]
Sorry. I forgot to add proper credits in my script, but this will be done in v8.7 

Thanks!
