### ISSUE TITLE
Verbose Mode

### ISSUE THREAD

**Issue by Klonkrieger2** [Piker-Alpha/RevoBoot#3]
Hi Pike,

it's Mark from your blog.

After installing revoboot, it hangs up after the grey boot logo screen appears.
How do i activate verbose mode?

Adding "-v" to the com.apple.boot.plist didn't help.

regards,
Mark

**Comment by Piker-Alpha** [comment]
Works here. Open RevoBoot/i386/config/SETTINGS/MacPro61.h (or whatever Mac model identifier you are using) and set:

DEBUG_BOOT 1

See if it locates com.apple.Boot.plist and also set these:

DEBUG_CPU 1
DEBUG_CPU_TURBO_RATIOS 1

This should help, but there are a number of other debug settings. One note. Debug messages are eating memory like crazy, so don't set too many at once.

**Comment by Klonkrieger2** [comment]
Thanks, for your help.

it seems that com.apple.boot.plist is not found. But why? Where has it to be?

Thats the bootscreen output:

![img_1873](https://f.cloud.github.com/assets/6315227/1843831/8446cf9a-74e4-11e3-9885-3ffe13c7712c.JPG)
![img_1872](https://f.cloud.github.com/assets/6315227/1843833/88781d1c-74e4-11e3-8628-14cd042e7b70.JPG)

**Comment by Piker-Alpha** [comment]
In the normal place: /Library/Preferences/SystemConfiguration/com.apple.Boot.plist

FSBFreq is set to 103 MHz, which is problematic for OS X because that expects 100 MHz (used to calculate stuff).

Also. Open RevoBoot/i386/libsaio/cpu/intel/dynamic_data.h and make sure you have this:

```
            case CPU_MODEL_IB_CORE:
            case CPU_MODEL_IB_CORE_EX:
            case CPU_MODEL_IB_CORE_XEON:
                CoreBridgeType = IVY_BRIDGE;
                hiBit = 31;
                break;
```

And in if(hiBit) {} you need to add something like:

```
            else if (strstr(gPlatform.CPU.BrandString, "Xeon(R)"))
            {
                gPlatform.CPU.Type = (0xA00 + CoreBridgeType);
            }
```

That should take care of the CPU type error (0x501) I see in the output. Please check this for me. Thanks.

**Comment by Klonkrieger2** [comment]
Hi!

great success pike! It's now booting and recognizing the CPU works much better now.
But I also seem to be quite stupid regarding the com.apple.boot.plist. It's in the correct folder like you said, but revoboot does not find it??? Maybe the problem is, that i have several HDDs, two with working OSX Installations (10.8.4 and 10.9.2)?

Also Graphics is not working due to lacking GraphicsEnabler=Yes but that seems to be a higher effort.
What are the next steps?
![foto 2](https://f.cloud.github.com/assets/6315227/1844455/40064a54-752a-11e3-875e-6d464cef050a.JPG)

**Comment by Piker-Alpha** [comment]
Right. That is much better. About the com.apple.Boot.plist problem. Are you booting from a USB stick? Remember this. RevoBoot will use the files from the first HDD thus the flag need to be set in com.apple.Boot.plist on that HDD (with proper permissions)

Now about the graphics card. I assume that GraphicsEnabler=yes sets EFI device-properties for you, and for that we have a nice extraction script: 

https://dl.dropboxusercontent.com/u/126585663/dpEdit.sh

Run this script. It will extract the properties for you and put them in a file (/Extra/EFI/MacPro61.[xml/bin]) that RevoBoot can use. You can use the same file until you replace the graphics card, or need to change other properties In that case you simply use this script and everything will be taken care of.

You can do the same with SMBIOS data. For this we have another tool:

RevoBoot/i386/libsaio/SMBIOS/tools/smbios2struct3.c

Compile with:

cc smbios2struct3.c -o smbios2struct3 -Wall -framework IOKit -framework CoreFoundation

No need to do the same task with every single boot. This makes it a one time event. Booting ultra fast.

**Comment by Klonkrieger2** [comment]
I tried out the dpEdit script, but it doesn't work for me:

sudo: /Users/test/Downloads/dpEdit.sh: command not found

I have no idea what the reason could be... the script itself looked ok for me.

No I'm booting from HDD. But the boot HDD has two partitions. I copied the boot.plist to the first partition. maybe whis will fix it.

Edit: yeah, that fixed it.

Edit2: the command not found issue, was caused by bad permissions. "chmod 755 dpedit.sh" fixed it!  :)

**Comment by Piker-Alpha** [comment]
Yeah. RevoBoot mimics the Apple boot loader and uses the first system partition.

Good to see that you solved the permission problem yourself.

I noticed that it shows six instead of 10 cores. Will look into this and try to figure out what is going on.

**Comment by Klonkrieger2** [comment]
okay, thanks.

It tried to inject the EFI string, but it seems that it's not loading. how can i check this? I placed the XML file in the correct folder.

DEBUG_EFI  didn't tell me that.

**Comment by Piker-Alpha** [comment]
Do you have: /Extra/EFI/MacPro61.bin ?
Also. dpEdit.sh should have changed this setting: #define INJECT_EFI_DEVICE_PROPERTIES               1
Did it?

Oh and open your settings file (MacPro61.h) and check this setting: STATIC_CPU_NumCores 10

**Comment by Klonkrieger2** [comment]
my settings-file is called default.h is that a problem?

oh, I only used the second option, to lad the efi bin file from Disk. Let me quickly test now..

STATIC_CPU_NumCores 10 already set.

**Comment by Klonkrieger2** [comment]
Awesome! Graphics is working now.

So, how do we go on now?

**Comment by Piker-Alpha** [comment]
Cool. 

Now check RevoBoot/MODEL and make sure you have "MacPro61" in it. This enables you to compile with just: ./r
Then you should have/use MacPro61.h as your settings file.

Is the CPU debug data now showing all cores? Oh and when you are done with debug data, then disable the compiler directive(s) to speed up the boot process.

I'll see if I can find some time to update the Github repo (maybe later today, but I want to check some stuff first).

p.s. Did you have to change the EFI setting or did dpEdit.h work for you?

**Comment by Klonkrieger2** [comment]
There is no folder RevoBoot/MODEL. Is there any disadvantage not having a macpro61.h file?

CPU debug says 10 cores and 20 threads, as you can see on the screenshot. Or do you mean the Max Turbo? That's also the same as before.

dpEdit.h did not change the EFI setting afaik. But I think it has to be in a special directory for doing that?

Just for understanding: Is revoboot creating a SSDT table internally? I noticed X86PlatformShim not loading anymore.

Or do I still have to use the sddt_pr.sh script and let the SSDT.aml load additionally?

**Comment by Piker-Alpha** [comment]
Ok. I changed the ./r script. Give it a try. Thanks!

And yes. For example. You may want to experiment with other Mac models (think EFI/SMBIOS settings) but without overwriting your current data. Also. Having files like: MacPro61.bin say something about the target model. default.h does not. You also don't want to load say Macmini62.bin when you in fact expect, or think, that RevoBoot loads MacPro61.bin files for your setup.

Yes I mean the mac Turbo lines. Seems like something is not working. I'll have a look when my wife goes to bed.

Edit: Oh wait. The other cores returned 0 (which we don't care about).

I have dpEdit.sh in my: /Extra/EFI/ directory and as long as you don't mess with the template... it should be fine.

No. Once you are done with the ACPI table setup, then you can add them to the boot loader. Creating one boot loader for a specific setup. And yes. That was why ssdtPRGen.sh was developed, and to make it work with all boot loaders.

**Comment by Piker-Alpha** [comment]
I think that this can be closed now, right? Please add new issues when you run into something with RevoBoot. 

Thanks!
