### ISSUE TITLE
SSDT_PR_GEN script issue: cpu-type=0x0a03

### ISSUE THREAD

**Issue by Klonkrieger2** [Piker-Alpha/RevoBoot#5]
HI Pike,

i think i found an issue in the ssdt script.

You found out that the cpu-type for the new xeon e5 v2 is 0xA0(x)

function _getCPUtype()
{
    #
    # Grab 'cpu-type' property from ioreg (stripped with sed / RegEX magic).
    #
    local grepStr=$(ioreg -p IODeviceTree -n "${gProcessorNames[0]}"@0 -k cpu-type | grep cpu-type | sed -e 's/ *[-|="<a-z>]//g')

```
# Swap bytes with help of ${str:pos:num}
#
echo ${grepStr:2:2}${grepStr:0:2}
```

}

the sed command is filtering out the "a". Isn't that a problem?

regards, 
mark

**Comment by Piker-Alpha** [comment]
Good catch. Should be fixed now. Thanks!

p.s. This is when I miss Jeroen. He was so much better than me with bash scripts
